# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artists',
        ),
    ]
