# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_delete_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('nation', models.CharField(max_length=250)),
                ('artist_logo', models.CharField(max_length=1000)),
            ],
        ),
    ]
